import { NextResponse } from "next/server";
import { deleteCampaign, getCampaign, updateCampaign, type CampaignStatus } from "@/lib/supabase-workspaces";
import { requireAuthenticatedUser } from "@/lib/supabase-db";
type Context = { params: Promise<{ id: string }> };
const statuses: CampaignStatus[] = ["draft", "active", "paused", "completed"];
function input(value: unknown) { if (!value || typeof value !== "object") return null; const b = value as Record<string, unknown>; const result: Record<string, string | null> = {}; if (b.name !== undefined) { if (typeof b.name !== "string" || !b.name.trim() || b.name.trim().length > 200) return null; result.name = b.name.trim(); } if (b.description !== undefined) { if (b.description !== null && typeof b.description !== "string") return null; result.description = typeof b.description === "string" ? b.description.trim() || null : null; } if (b.status !== undefined) { if (typeof b.status !== "string" || !statuses.includes(b.status as CampaignStatus)) return null; result.status = b.status; } if (b.template_id !== undefined) { if (b.template_id !== null && typeof b.template_id !== "string") return null; result.template_id = b.template_id as string | null; } return Object.keys(result).length ? result : null; }
function status(e: unknown) { return e instanceof Error && e.message === "UNAUTHENTICATED" ? 401 : 500; }
export async function GET(_r: Request, c: Context) { try { const { accessToken } = await requireAuthenticatedUser(); const { id } = await c.params; const campaign = await getCampaign(accessToken, id); return campaign ? NextResponse.json({ campaign }) : NextResponse.json({ error: "Campaign not found." }, { status: 404 }); } catch (e) { const s = status(e); return NextResponse.json({ error: s === 401 ? "Authentication required." : "Unable to load campaign." }, { status: s }); } }
export async function PATCH(request: Request, c: Context) { try { const { accessToken } = await requireAuthenticatedUser(); const { id } = await c.params; const data = input(await request.json().catch(() => null)); if (!data) return NextResponse.json({ error: "Invalid campaign data." }, { status: 400 }); const campaign = await updateCampaign(accessToken, id, data); return campaign ? NextResponse.json({ campaign }) : NextResponse.json({ error: "Campaign not found." }, { status: 404 }); } catch (e) { const s = status(e); return NextResponse.json({ error: s === 401 ? "Authentication required." : "Unable to update campaign." }, { status: s }); } }
export async function DELETE(_r: Request, c: Context) { try { const { accessToken } = await requireAuthenticatedUser(); const { id } = await c.params; return (await deleteCampaign(accessToken, id)) ? new NextResponse(null, { status: 204 }) : NextResponse.json({ error: "Campaign not found." }, { status: 404 }); } catch (e) { const s = status(e); return NextResponse.json({ error: s === 401 ? "Authentication required." : "Unable to delete campaign." }, { status: s }); } }
