import { NextResponse } from "next/server";
import { deleteTemplate, getTemplate, updateTemplate } from "@/lib/supabase-workspaces";
import { requireAuthenticatedUser } from "@/lib/supabase-db";

type Context = { params: Promise<{ id: string }> };
function input(value: unknown) { if (!value || typeof value !== "object") return null; const b = value as Record<string, unknown>; const result: Record<string, string> = {}; for (const key of ["name", "subject", "body"] as const) if (b[key] !== undefined) { if (typeof b[key] !== "string" || !b[key].trim()) return null; result[key] = b[key].trim(); } return Object.keys(result).length ? result : null; }
async function auth() { return requireAuthenticatedUser(); }
export async function GET(_request: Request, context: Context) { try { const { accessToken } = await auth(); const { id } = await context.params; const template = await getTemplate(accessToken, id); return template ? NextResponse.json({ template }) : NextResponse.json({ error: "Template not found." }, { status: 404 }); } catch (e) { return NextResponse.json({ error: e instanceof Error && e.message === "UNAUTHENTICATED" ? "Authentication required." : "Unable to load template." }, { status: e instanceof Error && e.message === "UNAUTHENTICATED" ? 401 : 500 }); } }
export async function PATCH(request: Request, context: Context) { try { const { accessToken } = await auth(); const { id } = await context.params; const data = input(await request.json().catch(() => null)); if (!data) return NextResponse.json({ error: "Invalid template data." }, { status: 400 }); const template = await updateTemplate(accessToken, id, data); return template ? NextResponse.json({ template }) : NextResponse.json({ error: "Template not found." }, { status: 404 }); } catch (e) { return NextResponse.json({ error: e instanceof Error && e.message === "UNAUTHENTICATED" ? "Authentication required." : "Unable to update template." }, { status: e instanceof Error && e.message === "UNAUTHENTICATED" ? 401 : 500 }); } }
export async function DELETE(_request: Request, context: Context) { try { const { accessToken } = await auth(); const { id } = await context.params; return (await deleteTemplate(accessToken, id)) ? new NextResponse(null, { status: 204 }) : NextResponse.json({ error: "Template not found." }, { status: 404 }); } catch (e) { return NextResponse.json({ error: e instanceof Error && e.message === "UNAUTHENTICATED" ? "Authentication required." : "Unable to delete template." }, { status: e instanceof Error && e.message === "UNAUTHENTICATED" ? 401 : 500 }); } }
